#!/bin/bash
mlp="$HOME/.local/share/man"
md_file="$mlp/markdown/$1.md"
if [[ ! -f "$md_file" ]]; then
    cat "$mlp/template.md" | sed "s|%name|$1|g" > "$md_file"
fi

nvim "$md_file"
kramdown --output man "$md_file" > "$mlp/mangnb/$1.gnb"
